name = "ink-drop"
compatibility_date = "2024-01-01"
main = "./dist/index.js"          # compiled output location


[[kv_namespaces]]
binding = "PASTE_KV"
id = "f362e0326b7a4c9cb92c82e56a8a3e28"
preview_id = "ae619d2507df4ac5baa7097a11b98793"

[[d1_databases]]
binding = "ink_drop_db"
database_name = "ink-drop-db"
database_id = "e8cefe08-3663-42f8-877b-afb599554534"

[build]
command = "npm run build"         # runs `tsc` → outputs to ./dist
cwd = "."
watch_dir = "./backend/src"